spring:
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}

security:
  client-id: ${CLIENT_ID}
  client-secret: ${CLIENT_SECRET}
  jwt:
    duration: ${JWT_DURATION}

cors:
  origins: ${CORS_ORIGINS}

market:
  twelve-data:
    api-key: ${TWELVE_DATA_API_KEY}