CREATE TABLE tb_role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    authority VARCHAR(255)
);

CREATE TABLE tb_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cpf VARCHAR(255) UNIQUE,
    password VARCHAR(255),
    name VARCHAR(255) UNIQUE,
    email VARCHAR(255) UNIQUE,
    nickname VARCHAR(255) UNIQUE
);

CREATE TABLE tb_portfolio (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE,
    cash_balance DOUBLE PRECISION,
    created_at TIMESTAMP,
    CONSTRAINT fk_portfolio_user FOREIGN KEY (user_id) REFERENCES tb_user (id)
);

CREATE TABLE tb_asset (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol VARCHAR(255),
    name VARCHAR(255),
    asset_type INTEGER,
    exchange VARCHAR(255),
    currency VARCHAR(255),
    tradable BOOLEAN
);

CREATE TABLE tb_position (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    average_price DOUBLE PRECISION,
    quantity INTEGER,
    realized_pnl DOUBLE PRECISION,
    asset_id BIGINT NOT NULL,
    portfolio_id BIGINT NOT NULL,
    CONSTRAINT fk_position_asset FOREIGN KEY (asset_id) REFERENCES tb_asset (id),
    CONSTRAINT fk_position_portfolio FOREIGN KEY (portfolio_id) REFERENCES tb_portfolio (id)
);

CREATE TABLE tb_user_role (
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_user_role_user FOREIGN KEY (user_id) REFERENCES tb_user (id),
    CONSTRAINT fk_user_role_role FOREIGN KEY (role_id) REFERENCES tb_role (id)
);
