CREATE TABLE tb_order (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    portfolio_id BIGINT NOT NULL,
    asset_id BIGINT NOT NULL,
    side VARCHAR(255),
    type VARCHAR(255),
    quantity INTEGER,
    limit_price DOUBLE PRECISION,
    status VARCHAR(255),
    created_at TIMESTAMP,
    executed_at TIMESTAMP,
    CONSTRAINT fk_order_portfolio FOREIGN KEY (portfolio_id) REFERENCES tb_portfolio (id),
    CONSTRAINT fk_order_asset FOREIGN KEY (asset_id) REFERENCES tb_asset (id)
);
