CREATE TABLE tb_execution (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    executed_price DOUBLE PRECISION,
    executed_quantity INTEGER,
    executed_at TIMESTAMP,
    CONSTRAINT fk_execution_order FOREIGN KEY (order_id) REFERENCES tb_order (id)
);
